### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by byronyi** [cyw617/taxi#2]
<code>Location currentLocation = mLocationClient.getLastLocation();</code>

In the <code>line 334</code> of <code>RequestActivity.java</code>, <code>mLocationClient.getLastLocation()</code> will return <code>null</code> if the App is the first client of GoogleMap, which will lead to an immediate failure of <code>line 621</code>.

<pre><code>protected String doInBackground(Location... params) {
    /*
    * Get a new geocoding service instance, set for localized addresses. This example uses
    * android.location.Geocoder, but other geocoders that conform to address standards
    * can also be used.
    */
    Geocoder geocoder = new Geocoder(localContext, Locale.getDefault());
 
    // Get the current location from the input parameter list
>   Location location = params[0];
</code></pre>

This statement will immediately fail if <code>params == null</code>, which is passed into <code>GetAddressTask</code> in line 340.

<pre><code>(new RequestActivity.GetAddressTask(this)).execute(currentLocation);
</code></pre>

Please see more details on this post <url>http://stackoverflow.com/questions/16830047/locationclient-getlastlocation-return-null</url>

**Comment by byronyi** [comment]
<pre><code>public void onConnected(Bundle bundle) {
    mConnectionStatus.setText(R.string.connected);
    startPeriodicUpdates();
    getAddress();
</code></pre>

As in the StackOverflow post, this <code>getAddress()</code> should not be called in <code>onConnected</code>. 
Move it to a more appropriate place.

**Comment by ywangbc** [comment]
The problem has been addressed in the customer project. Byron you may check it out and have a try as the emulator cannot pass google login on my computer whatsoever.

The detailed solution is as below:
I have used the while loop to make sure that the current location is not null. Thus we can ensure the mLocationClient.getLastLocation() is able to return not null address somehow. While this may not be an elegant way to address the problem, it could taken as a temp solution since the whole location service is going to be migrated to a service class later.

<pre><code>public void onConnected(Bundle bundle) {
    @Override
    public void onConnected(Bundle bundle) {
        mConnectionStatus.setText(R.string.connected);
        Location currentLoc = mLocationClient.getLastLocation();
                        while(currentLoc==null)
        {
            currentLoc = mLocationClient.getLastLocation();
        }
        LatLng locationNew = new LatLng(currentLoc.getLatitude(),currentLoc.getLongitude());
        CameraUpdate cameraup=CameraUpdateFactory.newLatLngZoom(locationNew,15);
        LocationUtils.mMap.animateCamera(cameraup);
        
        getAddress();
        startPeriodicUpdates();
}
</code></pre>

**Comment by ywangbc** [comment]
Another fix is that the address format of the previous code is quite strange. It will be something like:

1 University Rd Null Hong Kong.

The Null is here because there is no literally "city" in Hong Kong. Thus
<code>address.getLocality() </code> will return a null here. I have added code to handle this special case.

<pre><code>
                String addressText = getString(R.string.address_output_string,
                        // If there's a street address, add it
                        address.getMaxAddressLineIndex() > 0 ?
                                address.getAddressLine(0) : "",
                                // Locality is usually a city
                                address.getLocality() != null ?
                                address.getLocality() : "",
                                // The country of the address
                                address.getCountryName()
                        );
</code></pre>

**Comment by byronyi** [comment]
This is great. Now I understand what is your idea, and I agree that a quick hack is sufficient here.

I will work with @cyw617 after 6pm tomorrow on the service part. I plan to migrate our endpoint library to a service so we can update location in the background. Also the GCM part should be a service.

All of those are easy. Let's talk tomorrow.

**Comment by byronyi** [comment]
This issue will remain open until everyone seeing it once. It's not to criticise; instead, @ywangbc just did a wonderful demo on our new workflow.

@johcnhung @Tony-Mao Please check it out.

**Comment by cochung08** [comment]
okay.I am checking it out.  Btw,where shall we meet tonight @byronyi  ?

**Comment by byronyi** [comment]
This is resolved in #22
